import { Request, Response } from 'express';
import { sendSuccess } from '../utils/response';
import { fotmobService } from '../services/fotmob.service';

const EP = (p: string) => `/api${p}`;

const ENDPOINTS = [
  { method: 'GET', path: EP('/health'), desc: 'Health check + uptime' },
  { method: 'GET', path: EP('/home?timezone=Asia/Jakarta&ccode3=IDN'), desc: 'Feed layar utama: jadwal + live + trending + transfer' },
  { method: 'GET', path: EP('/matches/live?timezone=&ccode3='), desc: 'Skor live saat ini' },
  { method: 'GET', path: EP('/matches/live/stream?interval=&timezone=&ccode3='), desc: 'SSE live score (event: live tiap ~30 dtk)' },
  { method: 'GET', path: EP('/matches/today?timezone=&ccode3='), desc: 'Semua laga hari ini' },
  { method: 'GET', path: EP('/matches/tomorrow?timezone=&ccode3='), desc: 'Semua laga besok' },
  { method: 'GET', path: EP('/matches/yesterday?timezone=&ccode3='), desc: 'Semua laga kemarin' },
  { method: 'GET', path: EP('/matches/date/:date'), desc: 'Semua laga 1 hari (YYYY-MM-DD / YYYYMMDD)' },
  { method: 'GET', path: EP('/matches/range?from=&to=&timezone=&ccode3='), desc: 'Rentang tanggal (maks 51 hari)' },
  { method: 'GET', path: EP('/matches/notable'), desc: 'Laga pilihan hari ini' },
  { method: 'GET', path: EP('/leagues'), desc: 'Direktori semua liga' },
  { method: 'GET', path: EP('/leagues/grouped'), desc: 'Liga populer + grup benua siap-render' },
  { method: 'GET', path: EP('/league/:id'), desc: 'Detail liga full' },
  { method: 'GET', path: EP('/league/:id/overview?season='), desc: 'Agregat liga: detail + tabel + fixtures + stats' },
  { method: 'GET', path: EP('/league/:id/table?scope=all|home|away|form|xg'), desc: 'Klasemen ternormalisasi + legend zona' },
  { method: 'GET', path: EP('/league/:id/xg-table'), desc: 'Justice/xG table (xG, xGA, xPoints)' },
  { method: 'GET', path: EP('/league/:id/fixtures?season='), desc: 'Fixtures per musim' },
  { method: 'GET', path: EP('/league/:id/results?season='), desc: 'Hasil selesai per musim' },
  { method: 'GET', path: EP('/league/:id/topscorers?full=1'), desc: 'Top skor (topThree + full bila fetchAll tersedia)' },
  { method: 'GET', path: EP('/league/:id/topassists'), desc: 'Top assist' },
  { method: 'GET', path: EP('/league/:id/topkeepers'), desc: 'Top keeper (clean sheet/save)' },
  { method: 'GET', path: EP('/league/:id/cards'), desc: 'Ranking kartu' },
  { method: 'GET', path: EP('/league/:id/stats'), desc: 'Semua blok stats pemain+tim + topPlayers' },
  { method: 'GET', path: EP('/league/:id/news'), desc: 'Berita liga' },
  { method: 'GET', path: EP('/league/:id/difficulty'), desc: 'Fixture difficulty' },
  { method: 'GET', path: EP('/match/:id'), desc: 'Detail match mentah (lineup, stats, xG, shotmap, momentum, H2H)' },
  { method: 'GET', path: EP('/match/:id/overview'), desc: 'Ringkasan siap-render (skor, gol, kartu, topStats)' },
  { method: 'GET', path: EP('/match/:id/summary'), desc: 'Ringkasan singkat skor' },
  { method: 'GET', path: EP('/match/:id/events'), desc: 'Match facts/events' },
  { method: 'GET', path: EP('/match/:id/timeline'), desc: 'Timeline terurut (gol, kartu, subs, VAR)' },
  { method: 'GET', path: EP('/match/:id/statistics'), desc: 'Statistik periods + topStats + ratings' },
  { method: 'GET', path: EP('/match/:id/lineups'), desc: 'Lineup + formasi + coach + unavailable' },
  { method: 'GET', path: EP('/match/:id/ratings'), desc: 'Rating pemain + topPlayers + POTM' },
  { method: 'GET', path: EP('/match/:id/player-stats'), desc: 'Alias ratings' },
  { method: 'GET', path: EP('/match/:id/commentary'), desc: 'Liveticker + events + timeline' },
  { method: 'GET', path: EP('/match/:id/info'), desc: 'Venue, wasit (+stats), attendance, form, cuaca' },
  { method: 'GET', path: EP('/match/:id/shotmap'), desc: 'Shotmap xG per tembakan' },
  { method: 'GET', path: EP('/match/:id/heatmap'), desc: 'Heatmap URL + attacking zones' },
  { method: 'GET', path: EP('/match/:id/momentum'), desc: 'Grafik momentum' },
  { method: 'GET', path: EP('/match/:id/h2h'), desc: 'Head-to-head' },
  { method: 'GET', path: EP('/match/:id/table'), desc: 'Mini-table dari halaman match' },
  { method: 'GET', path: EP('/match/:id/media'), desc: 'Highlight video' },
  { method: 'GET', path: EP('/match/:id/highlights'), desc: 'Alias media' },
  { method: 'GET', path: EP('/match/:id/odds'), desc: 'Odds (null bila tidak tersedia)' },
  { method: 'GET', path: EP('/match/:id/tv?countryCode=ID'), desc: 'Jadwal TV' },
  { method: 'GET', path: EP('/team/:id'), desc: 'Detail klub (/club/:id alias)' },
  { method: 'GET', path: EP('/team/:id/overview'), desc: 'Agregat klub: next/last match, form, upcoming, results' },
  { method: 'GET', path: EP('/team/:id/squad'), desc: 'Skuad dikelompokkan (coach/keeper/def/mid/att)' },
  { method: 'GET', path: EP('/team/:id/fixtures'), desc: 'Fixtures tim (upcoming + nextMatch)' },
  { method: 'GET', path: EP('/team/:id/results'), desc: 'Hasil terakhir tim + form' },
  { method: 'GET', path: EP('/team/:id/stats?tournamentId='), desc: 'Statistik tim (per turnamen bila diisi)' },
  { method: 'GET', path: EP('/team/:id/statistics'), desc: 'Alias stats' },
  { method: 'GET', path: EP('/team/:id/news'), desc: 'Berita tim' },
  { method: 'GET', path: EP('/team/:id/transfers'), desc: 'Transfer masuk/keluar + rumor per tim' },
  { method: 'GET', path: EP('/team/:id/injuries'), desc: 'Cedera (kosong bila upstream tidak menyediakan)' },
  { method: 'GET', path: EP('/team/:id/suspensions'), desc: 'Skorsing (kosong bila upstream tidak menyediakan)' },
  { method: 'GET', path: EP('/team/:id/videos'), desc: 'Overview/venue tim' },
  { method: 'GET', path: EP('/player/:id'), desc: 'Detail pemain' },
  { method: 'GET', path: EP('/player/:id/overview'), desc: 'Ringkasan pemain + face + posisi + umur + value' },
  { method: 'GET', path: EP('/player/:id/statistics'), desc: 'Musim + liga utama + trofi' },
  { method: 'GET', path: EP('/player/:id/matches'), desc: 'Laga terakhir pemain' },
  { method: 'GET', path: EP('/player/:id/season'), desc: 'Alias statistics' },
  { method: 'GET', path: EP('/player/:id/history'), desc: 'Riwayat karier' },
  { method: 'GET', path: EP('/player/:id/transfers'), desc: 'Riwayat transfer dari karier' },
  { method: 'GET', path: EP('/player/:id/injuries'), desc: 'Info cedera pemain (null bila sehat)' },
  { method: 'GET', path: EP('/player/:id/news'), desc: 'Berita tim utama pemain' },
  { method: 'GET', path: EP('/player/:id/value'), desc: 'Market value history' },
  { method: 'GET', path: EP('/players?q='), desc: 'Cari pemain via search' },
  { method: 'GET', path: EP('/search/all?q='), desc: 'Search tim/pemain/liga/match/coach/referee' },
  { method: 'GET', path: EP('/search?q='), desc: 'Alias search/all' },
  { method: 'GET', path: EP('/search/suggest?term='), desc: 'Autocomplete mentah' },
  { method: 'GET', path: EP('/news'), desc: 'Berita dunia (page)' },
  { method: 'GET', path: EP('/news/latest?page='), desc: 'Berita terbaru' },
  { method: 'GET', path: EP('/news/breaking'), desc: 'Breaking (10 teratas)' },
  { method: 'GET', path: EP('/news/world?page='), desc: 'Berita dunia' },
  { method: 'GET', path: EP('/news/trending'), desc: 'Berita trending' },
  { method: 'GET', path: EP('/news/team/:id'), desc: 'Berita per tim' },
  { method: 'GET', path: EP('/news/player/:id'), desc: 'Berita tim utama pemain' },
  { method: 'GET', path: EP('/news/competition/:id'), desc: 'Berita per kompetisi' },
  { method: 'GET', path: EP('/transfers?limit='), desc: 'Bursa transfer (filter all)' },
  { method: 'GET', path: EP('/transfers/latest?limit='), desc: 'Transfer terbaru' },
  { method: 'GET', path: EP('/transfers/official?limit='), desc: 'Transfer resmi' },
  { method: 'GET', path: EP('/transfers/loans?limit='), desc: 'Transfer pinjaman' },
  { method: 'GET', path: EP('/transfers/free?limit='), desc: 'Transfer gratis' },
  { method: 'GET', path: EP('/transfers/rumours?teamId='), desc: 'Rumor (per tim bila teamId diisi)' },
  { method: 'GET', path: EP('/transfers/most-expensive?limit='), desc: 'Transfer termahal' },
  { method: 'GET', path: EP('/injuries'), desc: 'Info: cedera global tidak tersedia' },
  { method: 'GET', path: EP('/injuries/team/:id'), desc: 'Cedera per tim' },
  { method: 'GET', path: EP('/injuries/player/:id'), desc: 'Cedera per pemain' },
  { method: 'GET', path: EP('/stats/topscorers?leagueId='), desc: 'Top skor (+full list)' },
  { method: 'GET', path: EP('/stats/topassists?leagueId='), desc: 'Top assist' },
  { method: 'GET', path: EP('/stats/clean-sheets?leagueId='), desc: 'Clean sheets' },
  { method: 'GET', path: EP('/stats/cards?leagueId='), desc: 'Kartu' },
  { method: 'GET', path: EP('/stats/leaderboard/:metric?leagueId='), desc: 'Leaderboard: goals|assists|rating|xg|xa|shots|chances|passes|tackles|interceptions|recoveries|dribbles|cleansheets|saves|cards|minutes' },
  { method: 'GET', path: EP('/competition/:id/overview?season='), desc: 'Overview kompetisi (alias league)' },
  { method: 'GET', path: EP('/competition/:id/standings?scope='), desc: 'Klasemen kompetisi' },
  { method: 'GET', path: EP('/competition/:id/fixtures?season='), desc: 'Fixtures kompetisi' },
  { method: 'GET', path: EP('/competition/:id/results?season='), desc: 'Hasil kompetisi' },
  { method: 'GET', path: EP('/competition/:id/topscorers?full=1'), desc: 'Top skor kompetisi' },
  { method: 'GET', path: EP('/competition/:id/topassists'), desc: 'Top assist kompetisi' },
  { method: 'GET', path: EP('/competition/:id/topkeepers'), desc: 'Top keeper kompetisi' },
  { method: 'GET', path: EP('/competition/:id/cards'), desc: 'Kartu kompetisi' },
  { method: 'GET', path: EP('/competition/:id/stats'), desc: 'Stats kompetisi' },
  { method: 'GET', path: EP('/competition/:id/xg-table'), desc: 'xG table kompetisi' },
  { method: 'GET', path: EP('/tools/fifa-rankings'), desc: 'FIFA rankings (null = tidak tersedia upstream)' },
  { method: 'GET', path: EP('/tools/team-of-the-week'), desc: 'TOTW (status ketersediaan)' },
  { method: 'GET', path: EP('/tools/predictor'), desc: 'Info predictor' },
  { method: 'GET', path: EP('/tools/lineup-builder'), desc: 'Meta lineup builder' },
  { method: 'GET', path: EP('/tools/tv?matchId=&countryCode=ID'), desc: 'Jadwal TV per match' },
];

export const docsController = {
  // GET /api/docs — daftar endpoint + contoh ID valid
  getDocs: (_req: Request, res: Response) => {
    sendSuccess(res, {
      name: 'Football Live API',
      version: '3.3.0',
      nullSemantics: 'NULL = data tidak tersedia dari upstream; bukan nol. Tampilkan "N/A" di client bila null.',
      sampleIds: {
        leagueId: 47,
        teamId: 9825,
        playerId: 30981,
        matchId: 5795450,
        date: '2026-09-15',
        season: '2026/2027',
      },
      endpoints: ENDPOINTS,
    });
  },

  // GET /api/health
  getHealth: (_req: Request, res: Response) => {
    sendSuccess(res, { status: 'ok', uptime: Math.floor(process.uptime()), time: new Date().toISOString() });
  },
};

export function endpointList(): typeof ENDPOINTS {
  return ENDPOINTS;
}
